select = [
    "B",   # flake8-bugbear
    # "C4",  # flake8-comprehensions
    # "COM", # flake8-commas
    # "E",   # pycodestyle Error
    # "F",   # Pyflakes
    # "I",   # isort
    # "PERF",# Perflint
    # "PIE", # flake8-pie
#    "PT",  # flake8-pytest-style, would be nice to enable
    # "RET", # flake8-return
    # "RUF", # Ruff-specific rules
    # "SIM", # flake8-simplify
    # "UP",  # pyupgrade
    # "W",   # pycodestyle Warning
]
ignore = [
    "B017", # assert-raises-exception
    "B022", # useless-contextlib-suppress
    "RUF003"# Comment contains ambiguous character
]

line-length = 100
target-version = "py39"
