# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

# Install dependencies from setup.cfg as rpm packages for specfile
- name: Download script setupcfg2rpm.py
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/packit/deployment/main/scripts/setupcfg2rpm.py
    dest: ./setupcfg2rpm.py
    mode: 0775
  register: fetch_setupcfg2rpm
  until: fetch_setupcfg2rpm is not failed
  retries: 6

- name: Download specfile setup.cfg
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/packit/specfile/{{ source_branch }}/setup.cfg
    dest: ./specfile_setup.cfg
    mode: 0664
  register: fetch_specfile_setup
  until: fetch_specfile_setup is not failed
  retries: 6

- name: Replace rpm-py-installer with rpm
  ansible.builtin.replace:
    path: ./specfile_setup.cfg
    regexp: "rpm-py-installer"
    replace: "rpm"

- name: Install specfile dependencies provided by setupcfg2rpm
  ansible.builtin.shell: dnf install -y $(./setupcfg2rpm.py specfile_setup.cfg)
  args:
    warn: false
  become: true
  changed_when: true

# this is noop as python3-rpm is already installed, but it satisfies pip check
- name: Install rpm-py-installer using pip
  pip:
    name: rpm-py-installer
    executable: pip3
