# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

# Install dependencies from setup.cfg as rpm packages for ogr
- name: Download script setupcfg2rpm.py
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/packit/deployment/main/scripts/setupcfg2rpm.py
    dest: ./setupcfg2rpm.py
    mode: 0775
  register: fetch_setupcfg2rpm
  until: fetch_setupcfg2rpm is not failed
  retries: 6

- name: Download ogr setup.cfg
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/packit/ogr/{{ source_branch }}/setup.cfg
    dest: ./ogr_setup.cfg
    mode: 0664
  register: fetch_ogr_setup
  until: fetch_ogr_setup is not failed
  retries: 6

- name: Install ogr dependencies provided by setupcfg2rpm
  ansible.builtin.shell: dnf install -y $(./setupcfg2rpm.py ogr_setup.cfg)
  args:
    warn: false
  become: true
  changed_when: true
