# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Install dependencies for packit-service worker
  hosts: all
  vars:
    source_branch: "{{ lookup('env', 'SOURCE_BRANCH') }}"
  tasks:
    - import_tasks: tasks/process-source-branch.yaml
    - name: Pip-install gevent & greenlet
      # greenlet < 2.0.1 (required by gevent < 22) leaks memory on Python-3.11 (RHBZ#2158732)
      # Install gevent >= 22 (requires greenlet>2) before python3-sqlalchemy RPM
      # which would otherwise pull in greenlet<2 RPM
      pip:
        name:
          - gevent==22.*
        executable: pip3
    - name: Install all RPM/python packages needed to run packit-service worker
      dnf:
        name:
          - python3-ipdb # for easy debugging
          - nss_wrapper # openshift anyuid passwd madness
          - python3-requests
          - python3-prometheus_client
          - python3-sqlalchemy
          - python3-psycopg2
          - python3-redis # celery[redis]
          - python3-lazy-object-proxy
          - dnf-utils
          - make
          # for pip-installing sandcastle from git repo
          - git-core
          # oc rsync /tmp/sandcastle -> sandcastle pod
          - rsync
          - postgresql # pg_dump
          - python3-boto3 # AWS (S3)
          - python3-fasjson-client
          - bodhi-client
        state: present
        install_weak_deps: False
    - name: Install pip deps
      pip:
        name:
          - git+https://github.com/packit/sandcastle.git@{{ source_branch }}
          # The above bodhi-client RPM installs python3-requests-2.25.1 and python3-urllib3-1.26.5
          # The below sentry_sdk would then install urllib3-2.x because of its urllib3>=1.26.11 requirement
          # and 'pip check' would then scream that "requests 2.25.1 has requirement urllib3<1.27"
          - urllib3<1.27
          - sentry-sdk
          - syslog-rfc5424-formatter # Logging to Splunk
          - celery==5.2.* # celery-5.3.0b1 doesn't play well with flower
        executable: pip3
    - name: Check if all pip packages have all dependencies installed
      command: pip check
    - import_tasks: tasks/setup-copr-repos.yaml
    - name: Install ogr, specfile and packit from copr
      dnf:
        name:
          - python3-ogr
          - python3-specfile
          - packit
        state: latest
    - name: Install OKD CLI (oc) # sandcastle
      ansible.builtin.unarchive:
        src: https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        remote_src: true
        dest: /usr/bin/
