# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Install dependencies for packit-service
  hosts: all
  vars:
    source_branch: "{{ lookup('env', 'SOURCE_BRANCH') }}"
  tasks:
    - import_tasks: tasks/process-source-branch.yaml
    - name: Install all RPM/python packages needed to run packit-service
      dnf:
        name:
          - python3-ipdb # for easy debugging
          - python3-click
          - git # setuptools-scm
          # httpd & deps
          - python3-mod_wsgi
          - mod_ssl
          - python3-alembic
          - python3-sqlalchemy
          - python3-psycopg2
          - python3-prometheus_client
          - python3-redis # celery[redis]
          - python3-lazy-object-proxy
          - python3-flask-restx
          - python3-flask-talisman
          - python-jwt
          - bodhi-client
          # This is to be able to provide service version via API
          - python-setuptools_scm
        state: present
        install_weak_deps: False
    - name: Install pip deps
      pip:
        name:
          # The above bodhi-client RPM installs python3-requests-2.25.1 and python3-urllib3-1.26.5
          # The below sentry_sdk would then install urllib3-2.x because of its urllib3>=1.26.11 requirement
          # and 'pip check' would then scream that "requests 2.25.1 has requirement urllib3<1.27"
          - urllib3<1.27
          - sentry-sdk[flask]
          - syslog-rfc5424-formatter
          - celery==5.2.* # RPM not available on c9s
          - flask-cors # RHBZ#2100076
          - flexmock # because of alembic (d90948124e46_..._.py )
        executable: pip3
    - name: Check if all pip packages have all dependencies installed
      command: pip check
    - import_tasks: tasks/setup-copr-repos.yaml
    - name: Install ogr, specfile and packit from copr
      dnf:
        name:
          - python3-ogr
          - python3-specfile
          - packit
        state: latest
