# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Install dependencies for packit-service worker
  hosts: all
  vars:
    source_branch: "{{ lookup('env', 'SOURCE_BRANCH') }}"
  tasks:
    - import_tasks: tasks/process-source-branch.yaml
    - name: Install all RPM/python packages needed to run packit-service worker
      dnf:
        name:
          - python3-ipdb # for easy debugging
          - nss_wrapper # openshift anyuid passwd madness
          - redis # redis-cli for debugging
          - python3-requests
          - python3-alembic
          - python3-prometheus_client
          - python3-sqlalchemy+postgresql
          - python3-celery # unfortunately, the probes don't work with this
          - python3-redis # celery[redis]
          - python3-lazy-object-proxy
          - dnf-utils
          - make
          # for pip-installing sandcastle from git repo
          - git-core
          # oc rsync /tmp/sandcastle -> sandcastle pod
          - rsync
          - postgresql # pg_dump
          - python3-boto3 # AWS (S3)
          - python3-fasjson-client
          - python3-eventlet # concurrency pool, see run_worker.sh
          - python3-gevent # concurrency pool, see run_worker.sh
          # v6 = bodhi-client, v5 = python3-bodhi{,-client}
          - bodhi-client
        state: present
    - name: Install pip deps
      pip:
        name:
          - git+https://github.com/packit/sandcastle.git@{{ source_branch }}
          - sentry-sdk
          - syslog-rfc5424-formatter
        executable: pip3
    - name: Check if all pip packages have all dependencies installed
      command: pip check
    - import_tasks: tasks/setup-copr-repos.yaml
    - name: Install ogr, specfile and packit from copr
      dnf:
        name:
          - python3-ogr
          - python3-specfile
          - packit
        state: latest
    - name: Install OKD CLI (oc) # sandcastle
      ansible.builtin.unarchive:
        src: https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        remote_src: true
        dest: /usr/bin/
