---
- name: Install dependencies for packit-service.
  hosts: all
  tasks:
  - name: Install all RPM/python packages needed to run packit-service.
    dnf:
      name:
      - mod_md
      - python3-flask
      - python3-ipdb  # for easy debugging
      - python3-mod_wsgi
      - git # setuptools-scm
      state: present
  - name: Install python3-packit from testing repo
    dnf:
      name:
      # web service needs packit just for few bits (see #109), so hopefully we don't need it from master and RPM is enough
      - python3-packit
      # can be removed once 0.6.0 is in stable
      enablerepo: testing
      state: present
