---
- name: Install dependencies for packit-service worker.
  hosts: all
  tasks:
  - name: Install all RPM/python packages needed to run packit-service worker.
    dnf:
      name:
      - python3-ipdb  # for easy debugging
      - nss_wrapper  # openshift anyuid passwd madness
      - python3-celery # (#107)
      - rebase-helper
      - python3-redis
      - redis  # redis-cli for debugging
      - origin-clients # for sandcastle
      - python3-kubernetes # for sandcastle
      state: present
  - name: Install sandcastle
    pip:
      name: git+https://github.com/packit-service/sandcastle.git
      executable: pip3
  - name: Install ogr from git master
    pip:
      name: git+https://github.com/packit-service/ogr.git
      executable: pip3
  # Whitelist
  - name: Install frambo from git master
    pip:
      name: git+https://github.com/user-cont/frambo.git
      executable: pip3
