# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Install dependencies for packit-service
  hosts: all
  vars:
    source_branch: "{{ lookup('env', 'SOURCE_BRANCH') }}"
  tasks:
    - import_tasks: tasks/process-source-branch.yaml
    - name: Install all RPM/python packages needed to run packit-service
      dnf:
        name:
          - python3-ipdb # for easy debugging
          - python3-click
          - git # setuptools-scm
          # httpd & deps
          - python3-mod_wsgi
          - mod_ssl
          - python3-pip # not included in base fedora:31 image, needed for next task
          # temporary dependencies
          - krb5-devel
          - gcc
          - python3-devel
          - python3-alembic
          - python3-sqlalchemy
          - python3-prometheus_client
          - python3-psycopg2
          - python3-celery
          - python3-redis # celery[redis]
          - python3-lazy-object-proxy
          - python3-flask-restx
          - python3-flexmock # because of the hack during the alembic upgrade
          # (see d90948124e46_add_tables_for_triggers_koji_and_tests.py )
          - python-jwt
          # workaround for https://github.com/fedora-infra/bodhi/issues/4660
          # we need to explicitly install here so that `tasks/install-packit-deps.yaml` doesn't pick up bodhi-client 6
          - https://kojipkgs.fedoraproject.org/packages/bodhi/5.7.5/1.fc35/noarch/python3-bodhi-5.7.5-1.fc35.noarch.rpm
          - https://kojipkgs.fedoraproject.org/packages/bodhi/5.7.5/1.fc35/noarch/python3-bodhi-client-5.7.5-1.fc35.noarch.rpm
        state: present
        # needed when installing from koji - there are no GPG-signed packages
        disable_gpg_check: true
    - name: Install pip deps
      pip:
        name:
          - persistentdict # still needed by one Alembic migration script
          - sentry-sdk[flask]
        executable: pip3
    - name: Check if all pip packages have all dependencies installed
      command: pip check
    - import_tasks: tasks/setup-copr-repos.yaml
    - name: Install packit from copr
      dnf:
        name: packit
        state: present
