---
- name: Install dependencies for packit-service.
  hosts: all
  tasks:
    - name: Install all RPM/python packages needed to run packit-service.
      dnf:
        name:
          - python3-flask-restplus
          - python3-ipdb # for easy debugging
          - python3-mod_wsgi
          - python3-click
          - git # setuptools-scm
          # httpd & deps
          - httpd
          - mod_md
          - mod_ssl
          - nss_wrapper
          # temporary workaround for sake of marhsmallow
          # - python3-packit
          - python3-pip # not included in base fedora:31 image, needed for next task
          # temporary depdendencies
          - krb5-devel
          - gcc
          - python3-devel
          - python3-alembic
          - python3-sqlalchemy
          - python3-psycopg2
        state: present
    - name: Install pip deps
      pip:
        name:
          - persistentdict
          # temporary workaround for sake of marhsmallow
          - git+https://github.com/packit-service/packit.git
        executable: pip3
