---
- name: Install dependencies for packit-service worker.
  hosts: all
  tasks:
    - name: Install all RPM/python packages needed to run packit-service worker.
      dnf:
        name:
          - python3-ipdb # for easy debugging
          - nss_wrapper # openshift anyuid passwd madness
          - redis # redis-cli for debugging
          - origin-clients # for sandcastle
          - python3-kubernetes # for sandcastle
          - python3-fedora # to access FAS
          - python3-requests
          - python3-alembic
          - python3-sqlalchemy
          - python3-psycopg2
          - python3-lazy-object-proxy
          #- python3-flask-restx # https://bugzilla.redhat.com/show_bug.cgi?id=1817535
          # To raise upon unknown config key (packit#782)
          # Remove once we base packit image on fedora:32 (which ships marshmallow v3)
          - https://jpopelka.fedorapeople.org/python3-marshmallow-3.5.1-1.fc31.noarch.rpm
        state: present
    - name: Install pip deps
      pip:
        name:
          - git+https://github.com/packit-service/sandcastle.git
          - persistentdict
          - sentry-sdk==0.14.2
          - flask-restx
        executable: pip3
