---
- name: Install dependencies for packit-service worker.
  hosts: all
  tasks:
    - name: Install all RPM/python packages needed to run packit-service worker.
      dnf:
        name:
          - python3-ipdb # for easy debugging
          - nss_wrapper # openshift anyuid passwd madness
          - redis # redis-cli for debugging
          - origin-clients # for sandcastle
          - python3-kubernetes # for sandcastle
          - python3-fedora # to access FAS
          - python3-requests
          - python3-alembic
          - python3-prometheus_client
          - python3-sqlalchemy
          - python3-psycopg2
          #- python3-celery # don't, the liveness probe doesn't work
          - python3-redis
          - python3-lazy-object-proxy
          - python3-bugzilla # python-bugzilla (not bugzilla) on PyPI
          - python3-backoff # Bugzilla class
          #- python3-flask-restx # needs Fedora 32
        state: present
    - name: Install pip deps
      pip:
        name:
          - git+https://github.com/packit-service/sandcastle.git
          - sentry-sdk
          - flask-restx
        executable: pip3
