---
- name: Build packit-service image form current src dir.
  hosts: all
  tasks:
  - name: Build packit-service image from current src dir
    command: "make build"
    args:
      chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
    become: true
