---
- name: Build packit-service image form current src dir.
  hosts: all
  vars:
    # Zuul base job redefines project_dir
    project_dir: "{{ playbook_dir }}/.."
  tasks:
    - name: Build service and worker images
      command: "make {{ item }}"
      args:
        chdir: "{{ project_dir }}"
      become: true
      with_items:
        - service
        - worker
      environment:
        SOURCE_BRANCH: "{{ zuul.branch }}"
