---
- name: Build packit-service image form current src dir.
  hosts: all
  tasks:
    - include_tasks: tasks/zuul-project-setup.yaml

    - name: Build service and worker images
      command: "make {{ item }}"
      args:
        chdir: "{{ project_dir }}"
      become: true
      with_items:
        - service
        - worker
      environment:
        SOURCE_BRANCH: "{{ zuul.branch }}"
