---
- name: This is a recipe for how to cook with packit-service worker
  hosts: all
  vars:
    home_path: "{{ lookup('env', 'HOME') }}"
    packit_service_path: /src-packit-service
    ansible_bender:
      base_image: docker.io/usercont/packit
      target_image:
        name: docker.io/usercont/packit-service-worker
        cmd: run_worker.sh
      working_container:
        volumes:
        - '{{ playbook_dir }}:{{ packit_service_path }}:Z'
  tasks:
  - import_tasks: packit-service.yaml
  - name: Copy gitconfig
    copy:
      src: gitconfig
      dest: '{{ home_path }}/.gitconfig'
  - name: Copy run_worker.sh
    copy:
      src: run_worker.sh
      dest: /usr/bin/run_worker.sh
      mode: 0777
