# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: This is a recipe for a container image where packit-service tests will run
  hosts: all
  tasks:
    - name: Install test RPM dependencies
      ansible.builtin.dnf:
        name:
          - python3-flexmock
          - tar
          - rsync
        state: present
    - name: Install pip deps
      ansible.builtin.pip:
        name:
          - requre
          - pytest==8.0.2
          - pytest-cov
          - pytest-flask
          - deepdiff
