---
- name: This is a recipe for a container image where packit-service tests will run
  hosts: all
  tasks:
    - name: Install test RPM dependencies
      dnf:
        name:
          # 0.10.5 causes a regression
          - python3-flexmock-0.10.4
          - tar
          - rsync
        state: present
    - name: Install pip deps
      pip:
        name:
          - requre
          - pytest
          - pytest-cov
          - pytest-flask
        executable: pip3
