---
# This playbook is running tests inside Zuul
- name: Run packit-service tests
  hosts: all
  vars:
    # Zuul base job redefines project_dir
    project_dir: "{{ playbook_dir }}/.."
  tasks:
    - name: Install podman
      dnf:
        name:
          - podman
        state: present
      become: true
    - name: Build the worker image
      command: "make worker"
      args:
        chdir: "{{ project_dir }}"
      environment:
        SOURCE_BRANCH: "{{ zuul.branch }}"
    - name: Run tests within a container
      command: "make check_in_container"
      args:
        chdir: "{{ project_dir }}"
      environment:
        COLOR: "no"
        SOURCE_BRANCH: "{{ zuul.branch }}"
