---
# This playbook is running tests inside Zuul
- name: Run packit-service tests
  hosts: all
  tasks:
    - include_tasks: tasks/zuul-project-setup.yaml
    - name: Run tests within a container
      command: "make check_in_container"
      args:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
      become: true
