---
# This playbook is running tests inside Zuul
- name: Run packit-service tests
  hosts: all
  tasks:
    - include_tasks: tasks/zuul-project-setup.yaml
    - name: Install podman
      dnf:
        name:
          - podman
        state: present
      become: true
    - name: Run tests within a container
      command: "make check_in_container"
      args:
        chdir: "{{ project_dir }}"
