---
- name: This is a recipe for how to run packit tests
  hosts: all
  tasks:
  - include_tasks: tasks/zuul-project-setup.yaml
  - name: Run tests
    command: "echo Tests"
    args:
      chdir: '{{ project_dir }}'
