---
# This playbook is running tests inside Zuul
- name: Run packit-service tests
  hosts: all
  vars:
    # Zuul base job redefines project_dir
    project_dir: "{{ playbook_dir }}/.."
  tasks:
    - name: Creates zuul secrets directory
      file:
        path: "{{ project_dir }}/secrets/dev"
        state: directory
    - name: Run tests which are executed within openshift
      command: make check-inside-openshift-zuul
      args:
        chdir: "{{ project_dir }}"
      become: true
      environment:
        SOURCE_BRANCH: "{{ zuul.branch }}"
