
- secret:
    name: ssh_config
    data:
      value: !encrypted/pkcs1-oaep
        - sQBIcG26zc7n46NfydT3q4SnP6DwdqS0yTkFKgYWqpRl5LAbDDDbwpwwoFHjc8Ofafo9J
          zysrMStO+8CxUBc0+bHHESFx0Y96AF6g9q2H4/JpA7+4EQPEQsAEBKaLgPd5w/tJvBlVQ
          8C3vhKsifPWCzTl3SaXSqplZz7ruPdInewQ6voF5LkEIBMs3kXw9PPneGyJmFt8n0jPAj
          FGJP3q+hlH78oimmiGkK5T4pGhSdGkn5Ff9wSqvOZhSWON2Clq1Zyqd0ZFqtQGbvVY6aJ
          +zZ3Cd7/jQIsxLjx4i2rgoByGW3dKKTWI1065A1o69/TWWKi6J/Jqj0fqaunmY70e/bwH
          CvaL3OBS5ZOmEfgL2MtGCANPmXwzbfVe85uZZoOrfWIpVTGBY1a3HuhtpquqoiMA5dNm6
          F7w8l53O6lSA7YZjfb4040yU6u5GKp0UG+QJF1AZ+MTS4F2OshQoMODtZHq74UV77PaZF
          zLVS14tTbqJNNZzo20Bn0OmqhnOQdUS4G3qo7+3GUGclT4FNM8G4ZKDKxyrgYVTLeyln3
          sE/+R96X2ND4Uk5AKLAeh9GdNOphQelQQVdC6PoZfFX7v1iurgFbfqe79Pa1PY80Ws3pN
          pvTwdNZeS/rWOPn0rzYnbUkEFEsu7mWEFDad4CpEb2uyRLV9FTPNG2Xyg1AW3U=
