- secret:
    name: ssh_config
    data:
      value: !encrypted/pkcs1-oaep
        - DV6AV8SIrQtm4bEyHsYuHzRF55g5gZ4LMM+MJ5C9+Kq8WGRf4/+TgcekfHO5ETvz2Aixl
          TxEGxPBgXVjHB2rMoFdB5iI89h8qT6N/+ey3Y2GwgU0JzDzfLbWF6fkKSncoMr/WpwmX5
          OerFW+G8W9f6aCLlzMSzPd3BAG/5eFAvg7FfJ6wFajE4Y8Vh1cuJS9aXJYElRgrjq/YQD
          RyjaZ3ffZWZmJ9rOmmUMO1Ea7hj5aF4ig4rNHtVB/DHjV16eWJbSh1pw/JZWuzpd05XtX
          BlohYzV2O+H4cKzm2P1xmrXujkT4JrZFrvZMpzxi1lj9X1r73yNYU/7YhwN/lKbXTr9RC
          NCd4QdmLHekTZqDbVaJeW4YieqH/yhQnYkSqkwWJFB6Ko5fuugvYmkq+XI6ZbMmGbPyV1
          4+choC/VA82Jy0+Jbvx8VddTM5D3rBNZ/hvv632iAfibnR16/utXCSfOIwCPxisgkqtw4
          VvK2x8P36BqV/pVhHamv+GyeF8Av0wCZuXAMpNCTWPZW+rmqQYUMKoSBMJfXl3Dz5SJut
          josk8pW1t3+ufOnz8seuTXLiJTST/rkcYbb3GhKij25ndRt2Z0Xpv/pGJgU0ptNY8m4vc
          qE+SAb2vci97ISvpOHV05COMiBea7Klt/vzPL95dDjxgmn6ycZAQqp+xbQwH30=
