name: Rebuild & push worker:stg
on:
  push:
    branches: [main]

jobs:
  build:
    # To not run in forks
    if: github.repository == 'packit/packit-service'

    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        id: build-image
        # https://github.com/marketplace/actions/buildah-build
        uses: redhat-actions/buildah-build@v2
        with:
          dockerfiles: files/docker/Dockerfile.worker
          image: packit-worker
          tags: stg
          oci: true
          build-args: |
            SOURCE_BRANCH=main

      - name: Push To Quay
        # https://github.com/marketplace/actions/push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/packit
          username: ${{ secrets.QUAY_IMAGE_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_BUILDER_TOKEN }}
